# Generated by Django 4.2.11 on 2024-04-21 04:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('pg_type', models.CharField(choices=[('1*', '1*'), ('2*', '2*'), ('3*', '3*'), ('4*', '4*')], max_length=5)),
                ('no_of_person', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], default='one', max_length=5)),
                ('wifi', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('maid', models.BooleanField(default=False)),
                ('arrival_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_date', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(max_length=10)),
                ('sharing', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pg_type', models.CharField(choices=[('1*', '1*'), ('2*', '2*'), ('3*', '3*'), ('4*', '4*')], max_length=5, verbose_name='PG Type')),
                ('available_from', models.DateField(default=django.utils.timezone.now)),
                ('available_to', models.DateField(default=django.utils.timezone.now)),
                ('no_of_person', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], default='one', max_length=5)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('area', models.CharField(choices=[('vadaj', 'Vadaj'), ('ranip', 'Ranip'), ('cg road', 'CG Road'), ('naranpura', 'Naranpura'), ('navarangpura', 'Navarangpura')], max_length=20)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.BigIntegerField(default=0)),
                ('message', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitiesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('contact', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('pg_type', models.CharField(choices=[('1*', '1*'), ('2*', '2*'), ('3*', '3*'), ('4*', '4*')], max_length=5, verbose_name='PG Type')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sharing', models.CharField(max_length=20)),
                ('wifi', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('maid', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_no', models.BigIntegerField(default=0, verbose_name='A/C No')),
                ('ini_balance', models.IntegerField(default=0, verbose_name='Initial Balance')),
                ('rem_balance', models.IntegerField(default=0, verbose_name='Remaining Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('pg_type', models.CharField(choices=[('1*', '1*'), ('2*', '2*'), ('3*', '3*'), ('4*', '4*')], max_length=5, verbose_name='PG Type')),
                ('comfort', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=20)),
                ('quality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEapp.owner')),
            ],
        ),
    ]
