# Generated by Django 4.2.11 on 2024-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkavailability',
            name='area',
            field=models.CharField(choices=[('marathahalli', 'marathahalli'), ('HSR Layout', 'HSR Layout'), ('mg road', 'mg Road'), ('BTM layout', 'BTM layout'), ('Basavangudi', 'Basavangudi')], max_length=20),
        ),
    ]
