# Generated by Django 4.2.11 on 2024-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEapp', '0002_alter_checkavailability_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='food',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='laundry',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='maid',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='wifi',
            field=models.BooleanField(null=True),
        ),
    ]
